before_install:
  - sudo apt-get -y -q update
  - sudo apt-get -y -q install curl make libgc-dev libsqlite3-dev
  - git clone --depth=1 git://github.com/fasterthanlime/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - cd samples
  - mkdir -p travis
  - rock -v simple.ooc -o=travis/simple && travis/simple

